### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by jakeonfire** [khaledez/thrift-docker#1]
thanks for making this. it's exactly what i needed. ❤️ 

one suggestion: if you make the thrift version an `ARG` then it can be configured at build time ✨

**Comment by khaledez** [comment]
That's a good idea, will try and test it. Thanks for the star

**Comment by khaledez** [comment]
BTW, you can already use the image from docker hub: https://hub.docker.com/r/khaledez/thrift

**Comment by khaledez** [comment]
I updated Dockerfile to support args, and published a new version of thrift: https://hub.docker.com/r/khaledez/thrift.

Thanks !
